Product:
    type: entity
    table: product
    indexes:
        category_id:
            columns:
                - category_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 60
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        visible:
            type: boolean
            nullable: true
            comment: ''
        created:
            type: datetime
            nullable: true
            comment: ''
    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        tag:
            targetEntity: Tag
            cascade: {  }
            mappedBy: null
            inversedBy: product
            joinTable:
                name: product_tag
                joinColumns:
                    -
                        name: product_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: tag_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
